return {
  {
    "nvim-treesitter/nvim-treesitter",
    event = { "BufRead", "BufNewFile" }, -- 当读取文件或创建新文件时加载
    opts = function(_, opts)
      opts.ensure_installed = {}
      vim.list_extend(opts.ensure_installed, {
        "bibtex",
        "cmake",
        "cpp",
        "rust",
        "ron",
        -- "comment", -- comments are slowing down TS bigtime, so disable for now
        "css",
        "devicetree",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "glsl",
        "go",
        "gotmpl",
        "yaml",
        "gomod",
        "gowork",
        "gosum",
        "graphql",
        "http",
        "markdown",
        "markdown_inline",
        "kconfig",
        "meson",
        "ninja",
        "rst",
        "nix",
        "org",
        "php",
        "python",
        "requirements",
        "latex",
        "scss",
        "sql",
        "svelte",
        "vue",
        "wgsl",
        "zig",
        "json5",
        "helm",
        "lua",
        "xml",
        "json",
        "wit",
        "proto",
        "javascript",
        "typescript",
        "haskell",
        "java",
      })
    end,
  },
  {
    "davidmh/mdx.nvim",
    config = true,
    dependencies = { "nvim-treesitter/nvim-treesitter" },
  },
}
