return {
  {
    "williamboman/mason.nvim",
    optional = false,
    opts = {
      ensure_installed = {
        "codelldb",
        "clangd",
        "clang-format",
        "cmakelang",
        "cmakelint",
        "goimports",
        "gofumpt",
        "gomodifytags",
        "impl",
        "delve",
        "markdownlint-cli2",
        "markdown-toc",
        "zls",
        "texlab",
        "js-debug-adapter",
        "eslint-lsp",
        "json-lsp",
        "prettier",
        "yaml-language-server",
        "typescript-language-server",
        "tailwindcss-language-server",
        "ansible-lint",
        "ltex-ls",
        "hadolint",
        "haskell-language-server",
        "haskell-debug-adapter",
      },
    },
  },
}
